"""创建初始表结构（blood_pressure_records 和 appointments）

Revision ID: c4d9ebc46af7
Revises: 
Create Date: 2025-11-07 09:50:24.722136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c4d9ebc46af7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 注意：此迁移脚本仅更新业务表（blood_pressure_records 和 appointments）
    # LangGraph 的表（checkpoints, store 等）不在管理范围内，不应删除
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('appointments', 'id',
               existing_type=sa.INTEGER(),
               comment='预约ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('appointments', 'user_id',
               existing_type=sa.VARCHAR(length=255),
               comment='用户ID',
               existing_nullable=False)
    op.alter_column('appointments', 'department',
               existing_type=sa.VARCHAR(length=255),
               comment='科室',
               existing_nullable=False)
    op.alter_column('appointments', 'doctor_id',
               existing_type=sa.VARCHAR(length=255),
               comment='医生ID',
               existing_nullable=True)
    op.alter_column('appointments', 'doctor_name',
               existing_type=sa.VARCHAR(length=255),
               comment='医生姓名',
               existing_nullable=True)
    op.alter_column('appointments', 'appointment_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               comment='预约时间',
               existing_nullable=False)
    op.alter_column('appointments', 'status',
               existing_type=sa.VARCHAR(length=50),
               comment='预约状态（pending/completed/cancelled）',
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('appointments', 'notes',
               existing_type=sa.TEXT(),
               comment='备注',
               existing_nullable=True)
    op.alter_column('appointments', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('appointments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               comment='更新时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('blood_pressure_records', 'id',
               existing_type=sa.INTEGER(),
               comment='记录ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('blood_pressure_records', 'user_id',
               existing_type=sa.VARCHAR(length=255),
               comment='用户ID',
               existing_nullable=False)
    op.alter_column('blood_pressure_records', 'systolic',
               existing_type=sa.INTEGER(),
               comment='收缩压（范围：50-300）',
               existing_nullable=False)
    op.alter_column('blood_pressure_records', 'diastolic',
               existing_type=sa.INTEGER(),
               comment='舒张压（范围：30-200）',
               existing_nullable=False)
    op.alter_column('blood_pressure_records', 'measurement_time',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               comment='测量时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('blood_pressure_records', 'original_time_description',
               existing_type=sa.TEXT(),
               comment='原始时间描述（用户输入的时间描述）',
               existing_nullable=True)
    op.alter_column('blood_pressure_records', 'notes',
               existing_type=sa.TEXT(),
               comment='备注',
               existing_nullable=True)
    op.alter_column('blood_pressure_records', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('blood_pressure_records', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               comment='更新时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # 注意：此迁移脚本仅回滚业务表的更改
    # LangGraph 的表（checkpoints, store 等）不在管理范围内，不应重新创建
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('blood_pressure_records', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='更新时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('blood_pressure_records', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('blood_pressure_records', 'notes',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='备注',
               existing_nullable=True)
    op.alter_column('blood_pressure_records', 'original_time_description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='原始时间描述（用户输入的时间描述）',
               existing_nullable=True)
    op.alter_column('blood_pressure_records', 'measurement_time',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='测量时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('blood_pressure_records', 'diastolic',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='舒张压（范围：30-200）',
               existing_nullable=False)
    op.alter_column('blood_pressure_records', 'systolic',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='收缩压（范围：50-300）',
               existing_nullable=False)
    op.alter_column('blood_pressure_records', 'user_id',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='用户ID',
               existing_nullable=False)
    op.alter_column('blood_pressure_records', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='记录ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('appointments', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='更新时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('appointments', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('appointments', 'notes',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='备注',
               existing_nullable=True)
    op.alter_column('appointments', 'status',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='预约状态（pending/completed/cancelled）',
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('appointments', 'appointment_date',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='预约时间',
               existing_nullable=False)
    op.alter_column('appointments', 'doctor_name',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='医生姓名',
               existing_nullable=True)
    op.alter_column('appointments', 'doctor_id',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='医生ID',
               existing_nullable=True)
    op.alter_column('appointments', 'department',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='科室',
               existing_nullable=False)
    op.alter_column('appointments', 'user_id',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='用户ID',
               existing_nullable=False)
    op.alter_column('appointments', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='预约ID',
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###
