spring:
  profiles:
    active: chat
  ai:
    mcp:
      client:
        enabled: true
        name: shuxl-mcp-client
        version: 1.0.0
        request-timeout: 30s
        type: SYNC
        sse:
          connections:
            server1:
              url: http://localhost:9092
#            server2:
#              url: http://otherserver:8081
#              sse-endpoint: /custom-sse

server:
  port: 9093